# Generated by Django 5.2 on 2025-04-14 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the asset (e.g., 'Office 365 E3', 'example.com')",
                        max_length=255,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("LIC", "License"),
                            ("DOM", "Domain"),
                            ("SSL", "SSL Certificate"),
                            ("SUB", "Software Subscription"),
                        ],
                        help_text="The type of the asset",
                        max_length=3,
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Vendor or provider (e.g., 'Microsoft', 'GoDaddy')",
                        max_length=255,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        help_text="Date the asset expires or needs renewal"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual or periodic cost",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "associated_department",
                    models.CharField(
                        blank=True,
                        help_text="Department associated with this asset",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "associated_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary user associated with this asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADM", "Admin"), ("VWR", "Viewer")],
                        default="VWR",
                        help_text="User role determining permissions",
                        max_length=3,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
